// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Run(argv []string, env []string, stdin io.Reader, stdout io.Writer, stderr io.Writer) error {
	ret := _mock.Called(argv, env, stdin, stdout, stderr)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string, []string, io.Reader, io.Writer, io.Writer) error); ok {
		r0 = returnFunc(argv, env, stdin, stdout, stderr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockExecutor_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - argv []string
//   - env []string
//   - stdin io.Reader
//   - stdout io.Writer
//   - stderr io.Writer
func (_e *MockExecutor_Expecter) Run(argv any, env any, stdin any, stdout any, stderr any) *MockExecutor_Run_Call {
	return &MockExecutor_Run_Call{Call: _e.mock.On("Run", argv, env, stdin, stdout, stderr)}
}

func (_c *MockExecutor_Run_Call) Run(run func(argv []string, env []string, stdin io.Reader, stdout io.Writer, stderr io.Writer)) *MockExecutor_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		var arg4 io.Writer
		if args[4] != nil {
			arg4 = args[4].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockExecutor_Run_Call) Return(err error) *MockExecutor_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_Run_Call) RunAndReturn(run func(argv []string, env []string, stdin io.Reader, stdout io.Writer, stderr io.Writer) error) *MockExecutor_Run_Call {
	_c.Call.Return(run)
	return _c
}
