// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIO creates a new instance of MockIO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIO {
	mock := &MockIO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIO is an autogenerated mock type for the IO type
type MockIO struct {
	mock.Mock
}

type MockIO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIO) EXPECT() *MockIO_Expecter {
	return &MockIO_Expecter{mock: &_m.Mock}
}

// Getenv provides a mock function for the type MockIO
func (_mock *MockIO) Getenv(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Getenv")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIO_Getenv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getenv'
type MockIO_Getenv_Call struct {
	*mock.Call
}

// Getenv is a helper method to define mock.On call
//   - key string
func (_e *MockIO_Expecter) Getenv(key any) *MockIO_Getenv_Call {
	return &MockIO_Getenv_Call{Call: _e.mock.On("Getenv", key)}
}

func (_c *MockIO_Getenv_Call) Run(run func(key string)) *MockIO_Getenv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIO_Getenv_Call) Return(s string) *MockIO_Getenv_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIO_Getenv_Call) RunAndReturn(run func(key string) string) *MockIO_Getenv_Call {
	_c.Call.Return(run)
	return _c
}

// ReadPassword provides a mock function for the type MockIO
func (_mock *MockIO) ReadPassword(fd int) ([]byte, error) {
	ret := _mock.Called(fd)

	if len(ret) == 0 {
		panic("no return value specified for ReadPassword")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]byte, error)); ok {
		return returnFunc(fd)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []byte); ok {
		r0 = returnFunc(fd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(fd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIO_ReadPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadPassword'
type MockIO_ReadPassword_Call struct {
	*mock.Call
}

// ReadPassword is a helper method to define mock.On call
//   - fd int
func (_e *MockIO_Expecter) ReadPassword(fd any) *MockIO_ReadPassword_Call {
	return &MockIO_ReadPassword_Call{Call: _e.mock.On("ReadPassword", fd)}
}

func (_c *MockIO_ReadPassword_Call) Run(run func(fd int)) *MockIO_ReadPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIO_ReadPassword_Call) Return(bytes []byte, err error) *MockIO_ReadPassword_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockIO_ReadPassword_Call) RunAndReturn(run func(fd int) ([]byte, error)) *MockIO_ReadPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Stderr provides a mock function for the type MockIO
func (_mock *MockIO) Stderr() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stderr")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockIO_Stderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stderr'
type MockIO_Stderr_Call struct {
	*mock.Call
}

// Stderr is a helper method to define mock.On call
func (_e *MockIO_Expecter) Stderr() *MockIO_Stderr_Call {
	return &MockIO_Stderr_Call{Call: _e.mock.On("Stderr")}
}

func (_c *MockIO_Stderr_Call) Run(run func()) *MockIO_Stderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIO_Stderr_Call) Return(writer io.Writer) *MockIO_Stderr_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockIO_Stderr_Call) RunAndReturn(run func() io.Writer) *MockIO_Stderr_Call {
	_c.Call.Return(run)
	return _c
}

// Stdin provides a mock function for the type MockIO
func (_mock *MockIO) Stdin() io.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdin")
	}

	var r0 io.Reader
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	return r0
}

// MockIO_Stdin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdin'
type MockIO_Stdin_Call struct {
	*mock.Call
}

// Stdin is a helper method to define mock.On call
func (_e *MockIO_Expecter) Stdin() *MockIO_Stdin_Call {
	return &MockIO_Stdin_Call{Call: _e.mock.On("Stdin")}
}

func (_c *MockIO_Stdin_Call) Run(run func()) *MockIO_Stdin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIO_Stdin_Call) Return(reader io.Reader) *MockIO_Stdin_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *MockIO_Stdin_Call) RunAndReturn(run func() io.Reader) *MockIO_Stdin_Call {
	_c.Call.Return(run)
	return _c
}

// Stdout provides a mock function for the type MockIO
func (_mock *MockIO) Stdout() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdout")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockIO_Stdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdout'
type MockIO_Stdout_Call struct {
	*mock.Call
}

// Stdout is a helper method to define mock.On call
func (_e *MockIO_Expecter) Stdout() *MockIO_Stdout_Call {
	return &MockIO_Stdout_Call{Call: _e.mock.On("Stdout")}
}

func (_c *MockIO_Stdout_Call) Run(run func()) *MockIO_Stdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIO_Stdout_Call) Return(writer io.Writer) *MockIO_Stdout_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockIO_Stdout_Call) RunAndReturn(run func() io.Writer) *MockIO_Stdout_Call {
	_c.Call.Return(run)
	return _c
}
