// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFS creates a new instance of MockFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFS {
	mock := &MockFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFS is an autogenerated mock type for the FS type
type MockFS struct {
	mock.Mock
}

type MockFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFS) EXPECT() *MockFS_Expecter {
	return &MockFS_Expecter{mock: &_m.Mock}
}

// MkdirAll provides a mock function for the type MockFS
func (_mock *MockFS) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFS_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm os.FileMode
func (_e *MockFS_Expecter) MkdirAll(path any, perm any) *MockFS_MkdirAll_Call {
	return &MockFS_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockFS_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *MockFS_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFS_MkdirAll_Call) Return(err error) *MockFS_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *MockFS_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockFS
func (_mock *MockFS) ReadFile(name string) ([]byte, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFS_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFS_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name string
func (_e *MockFS_Expecter) ReadFile(name any) *MockFS_ReadFile_Call {
	return &MockFS_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *MockFS_ReadFile_Call) Run(run func(name string)) *MockFS_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFS_ReadFile_Call) Return(bytes []byte, err error) *MockFS_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFS_ReadFile_Call) RunAndReturn(run func(name string) ([]byte, error)) *MockFS_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockFS
func (_mock *MockFS) Rename(oldpath string, newpath string) error {
	ret := _mock.Called(oldpath, newpath)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldpath, newpath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockFS_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - oldpath string
//   - newpath string
func (_e *MockFS_Expecter) Rename(oldpath any, newpath any) *MockFS_Rename_Call {
	return &MockFS_Rename_Call{Call: _e.mock.On("Rename", oldpath, newpath)}
}

func (_c *MockFS_Rename_Call) Run(run func(oldpath string, newpath string)) *MockFS_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFS_Rename_Call) Return(err error) *MockFS_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_Rename_Call) RunAndReturn(run func(oldpath string, newpath string) error) *MockFS_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockFS
func (_mock *MockFS) Stat(name string) (os.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFS_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockFS_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *MockFS_Expecter) Stat(name any) *MockFS_Stat_Call {
	return &MockFS_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *MockFS_Stat_Call) Run(run func(name string)) *MockFS_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFS_Stat_Call) Return(v os.FileInfo, err error) *MockFS_Stat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockFS_Stat_Call) RunAndReturn(run func(name string) (os.FileInfo, error)) *MockFS_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// UserConfigDir provides a mock function for the type MockFS
func (_mock *MockFS) UserConfigDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserConfigDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFS_UserConfigDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserConfigDir'
type MockFS_UserConfigDir_Call struct {
	*mock.Call
}

// UserConfigDir is a helper method to define mock.On call
func (_e *MockFS_Expecter) UserConfigDir() *MockFS_UserConfigDir_Call {
	return &MockFS_UserConfigDir_Call{Call: _e.mock.On("UserConfigDir")}
}

func (_c *MockFS_UserConfigDir_Call) Run(run func()) *MockFS_UserConfigDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFS_UserConfigDir_Call) Return(s string, err error) *MockFS_UserConfigDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFS_UserConfigDir_Call) RunAndReturn(run func() (string, error)) *MockFS_UserConfigDir_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockFS
func (_mock *MockFS) WriteFile(name string, data []byte, perm os.FileMode) error {
	ret := _mock.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, os.FileMode) error); ok {
		r0 = returnFunc(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFS_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - name string
//   - data []byte
//   - perm os.FileMode
func (_e *MockFS_Expecter) WriteFile(name any, data any, perm any) *MockFS_WriteFile_Call {
	return &MockFS_WriteFile_Call{Call: _e.mock.On("WriteFile", name, data, perm)}
}

func (_c *MockFS_WriteFile_Call) Run(run func(name string, data []byte, perm os.FileMode)) *MockFS_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 os.FileMode
		if args[2] != nil {
			arg2 = args[2].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFS_WriteFile_Call) Return(err error) *MockFS_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_WriteFile_Call) RunAndReturn(run func(name string, data []byte, perm os.FileMode) error) *MockFS_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
